services:
  Drawer-Capture:
    image: drawer-capture-app:latest
    build: .
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
      - $HOME:/$HOME:rw
      - /dev:/dev
      - type: bind
        source: $HOME/named_pipes/
        target: /hostpipe
    network_mode: host