name: test qt elements
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os : [ubuntu-latest]
        python: ["3.10.12"]
    env:
      DISPLAY: ':99.0'
    steps:
    - name: get repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: setup ${{ matrix.os }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgles2-mesa-dev
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: gphoto2 libgphoto2-6 ffmpeg

    - name: install python test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-qt pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run tests
      run: |
        python -m pytest
